---
- name: "[{{ stack_name }}] Creating docker-compose directory"
  ansible.builtin.file:
    path: "{{ docker_compose_path }}"
    state: directory
    mode: "744"

- name: "[{{ stack_name }}] Deploying docker-compose file"
  ansible.builtin.template:
    src: docker-compose.yml
    dest: "{{ docker_compose_path }}/docker-compose.yml"
    mode: "744"

- name: "[{{ stack_name }}] Deploying .env file"
  ansible.builtin.template:
    src: .env.j2
    dest: "{{ docker_compose_path }}/.env"
    mode: "744"
  when: deploy_env_template

- name: "[{{ stack_name }}] Applying state {{ docker_compose_state }} to docker-compose"
  community.docker.docker_compose_v2:
    project_src: "{{ docker_compose_path }}"
    state: "{{ 'absent' if docker_compose_state == 'absent' else 'present' }}"
    restarted: "{{ docker_compose_state == 'restarted' }}"
    pull: true
